spring:
  redis:
    host: localhost #指定redis所在的host
    port: 6379  #指定redis的端口
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大空闲数
        min-idle: 0 #最小空闲数
        max-wait: 100ms #连接等待时间